### ISSUE TITLE
debian based distro

### ISSUE THREAD

**Issue by jack-dod** [YoyPa/isw#68] opened 2020-03-03 07:52 UTC
Hello, i am trying run isw on a debian based distro but the ec_sys is not a builtin module (sys/kernel/debug/ec/ec0/io does not exist).
Can you help?
If i run isw i will give you the ec dump because i have updated bios and ec on a gl62m 7rd (ec ver. 16j9ems1.112)

**Comment by hugglesfox** [comment] 2020-03-03 11:38
Duplicate of #61 

Out of interest, what Debian based distro are you using specifically?

**Comment by jack-dod** [comment] 2020-03-08 06:05
ok i tested it on ubuntu live and ec_sys does exist on ubuntu
i have a GL62M-7RD with **updated** bios (ver E16J9IMS.324) and ec (ver **16J9EMS1.112**)
it works on coolerboost and cpu fan but not on gpu fan

here my dump:

[gl62m-7rd_16J9EMS1.112.txt](https://github.com/YoyPa/isw/files/4322571/gl62m-7rd_16J9EMS1.112.txt)

And maybe is there a way to activate and deactivate the dedicated gpu (nvidia gtx 1050)?

**Closed as completed** 2020-06-09 08:29 UTC
